/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SipCalculatorRouteImport } from './routes/sip-calculator'
import { Route as IndexRouteImport } from './routes/index'

const SipCalculatorRoute = SipCalculatorRouteImport.update({
  id: '/sip-calculator',
  path: '/sip-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sip-calculator': typeof SipCalculatorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sip-calculator': typeof SipCalculatorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sip-calculator': typeof SipCalculatorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/sip-calculator'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/sip-calculator'
  id: '__root__' | '/' | '/sip-calculator'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SipCalculatorRoute: typeof SipCalculatorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sip-calculator': {
      id: '/sip-calculator'
      path: '/sip-calculator'
      fullPath: '/sip-calculator'
      preLoaderRoute: typeof SipCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SipCalculatorRoute: SipCalculatorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
